# Make sure to check the documentation at http://goreleaser.com
# https://goreleaser.com/customization/templates/
# https://goreleaser.com/customization/build/#reproducible-builds
project_name: signaller
before:
  hooks:
    - go mod download
builds:
  - &build
    id: signaller
    binary: signaller
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser 
    main: ./cmd/signaller/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
  -
    <<: *build
    id: signallee
    binary: signallee
    main: ./cmd/signallee


archives:
  - &archive
    id: signaller
    builds: ["signaller"]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  -
    <<: *archive
    id: signallee
    builds: ["signallee"]

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-rc-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: johnbuhay
    name: signaller


docker_manifests:
- name_template: jnbnyc/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - jnbnyc/{{ .ProjectName }}:{{ .Version }}-amd64
  - jnbnyc/{{ .ProjectName }}:{{ .Version }}-arm64v8

dockers:
- image_templates: ["jnbnyc/{{ .ProjectName }}:{{ .Version }}-amd64"]
  ids: [signaller]
  use_buildx: true
  dockerfile: cmd/signaller/Dockerfile
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  # - --label=org.opencontainers.image.description="Monitor a list of files and send a signal to a pid when they change"
  - --label=org.opencontainers.image.source=https://github.com/johnbuhay/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ .CommitTimestamp }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=APACHE
- image_templates: ["jnbnyc/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  ids: [signaller]
  use_buildx: true
  goarch: arm64
  dockerfile: cmd/signaller/Dockerfile
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description="Monitor a list of files and send a signal to a pid when they change"
  - --label=org.opencontainers.image.source=https://github.com/johnbuhay/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ .CommitTimestamp }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=APACHE
