# Make sure to check the documentation at http://goreleaser.com
# https://goreleaser.com/customization/templates/
# https://goreleaser.com/customization/build/#reproducible-builds
before:
  hooks:
    - go mod download
builds:
  - binary: signallee
    env:
      - CGO_ENABLED=0
    id: signallee
    main: ./cmd/signallee/
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
  - binary: signaller
    env:
      - CGO_ENABLED=0
    id: signaller
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}}"
    main: ./cmd/signaller/
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
# snapshot:
#   name_template: "{{ .Tag }}-rc"
# signs:
#   - artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: johnbuhay
    name: signaller